### ISSUE TITLE
Batch operation results in 'Error parsing HTTP message header byte 101 of message System.Byte[].'

### ISSUE THREAD

**Issue by troygNZ** [iwate/ODataHttpClient#19]
When calling an endpoint that contains a non 200 response for one of the calls, I get back
Error parsing HTTP message header byte 101 of message System.Byte[].

Note, not for all calls.

`   at System.Net.Http.HttpContentMessageExtensions.<ReadAsHttpResponseMessageAsyncCore>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at ODataHttpClient.ODataClient.<ParseMultiAsync>d__18.MoveNext()`

Quite possibly as a result of using ReadAsHttpRequestMessageAsync() as opposed to ReadAsStringAsync() ?
https://forums.asp.net/t/2037342.aspx?Max+header+size+when+serializing+HttpMessageContent

**Comment by iwate** [comment]
@troygNZ Thankyou for your bug report.
But  I cannot figure it out the cause. I need more detail.
Would you paste the response full body?

**Comment by troygNZ** [comment]
Thanks @iwate

Response example
```HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Content-Length: 118
location: 
dataserviceversion: 2.0

{"error":{"code":"","message":{"lang":"en","value":"E-mail address blah;;blah.coom isn't valid. Please check."}}}

```



Request example, with some sensitive data etc removed or adjusted

```POST /sap/c4c/odata/v1/c4codataapi/$batch HTTP/1.1
accept: multipart/mixed, application/json
authorization:                                   
request-context: appId=
request-id: 
traceparent: 
cookie: 
content-type: multipart/mixed; boundary="batcha5fc0546-bfb4-4f27-8d02-b7f3cb942604"
content-length: 1454
x-akamai-config-log-detail: true
te: chunked;q=1.0
connection: TE
accept-encoding: gzip
akamai-origin-hop: 1
via: 1.1 akamai.net(ghost) (AkamaiGHost)
x-forwarded-for: 
true-client-ip: 
host: 
pragma: no-cache
cache-control: no-cache, max-age=0
connection: keep-alive
debug-edgeserver-ip: 
x-sap-webdisp-target-group-no-redispatch: ODATA_LOAD
sap-web-dispatcher: version=7.81.0
clientprotocol: https
ssl_cipher_usekeysize: 
ssl_cipher_suite: 

--batcha5fc0546-bfb4-4f27-8d02-b7f3cb942604
content-type: multipart/mixed; boundary="changeset55e5e03c-c544-4952-9402-03e3f2fcc1f5"

--changeset55e5e03c-c544-4952-9402-03e3f2fcc1f5
content-type: application/http
content-transfer-encoding: binary

PATCH /sap/c4c/odata/v1/c4codataapi/ContactCollection('XXXXXXXXXXXXXXXXXXX') HTTP/1.1
Host: 
Accept: application/json, application/octet-stream, text/plain
Content-ID: 1
Content-Type: application/json; charset=utf-8

{"AccountID":"111111","LastName":"Aaaaa","FirstName":"CP1","TitleCode":null,"NickName":"","BirthName":"","Email":"blah;;blah.coom","ZCH_WebSite_KUT":null,"Mobile":"(0064) 211-123456","Phone":null,"ZCH_AfterHoursContact_KUT":null,"Fax":null}
--changeset55e5e03c-c544-4952-9402-03e3f2fcc1f5
content-type: application/http
content-transfer-encoding: binary

POST /sap/c4c/odata/v1/c4codataapi/ContactCollection HTTP/1.1
Host:
Accept: application/json, application/octet-stream, text/plain
Content-ID: 2
Content-Type: application/json; charset=utf-8

{"AccountID":"1321643","LastName":"Aaaaa","FirstName":"CP2","TitleCode":null,"NickName":"","BirthName":"","Email":"hello@world.com","ZCH_WebSite_KUT":null,"Mobile":null,"Phone":null,"ZCH_AfterHoursContact_KUT":null,"Fax":null}
--changeset55e5e03c-c544-4952-9402-03e3f2fcc1f5--

--batcha5fc0546-bfb4-4f27-8d02-b7f3cb942604--

```

**Comment by iwate** [comment]
@troygNZ thanks! I check it out.

**Comment by iwate** [comment]
memo:
https://github.com/dotnet/runtime/issues/27218

**Comment by iwate** [comment]
memo:

the error messages here.
https://github.com/aspnet/AspNetWebStack/blob/ba26cfbfbf958d548e4c0a96e853250f13450dc6/src/System.Net.Http.Formatting/Properties/Resources.resx#L156-L158

and use in
https://github.com/aspnet/AspNetWebStack/blob/ba26cfbfbf958d548e4c0a96e853250f13450dc6/src/System.Net.Http.Formatting/HttpContentMessageExtensions.cs#L257-L260

**Comment by iwate** [comment]
ParseState.Invalid from InternetMessageFormatHeaderParser.

https://github.com/aspnet/AspNetWebStack/blob/ba26cfbfbf958d548e4c0a96e853250f13450dc6/src/System.Net.Http.Formatting/Formatting/Parsers/InternetMessageFormatHeaderParser.cs#L166

https://github.com/aspnet/AspNetWebStack/blob/ba26cfbfbf958d548e4c0a96e853250f13450dc6/src/System.Net.Http.Formatting/Formatting/Parsers/InternetMessageFormatHeaderParser.cs#L235

**Comment by iwate** [comment]
@troygNZ Could you check line break code of the response? It need to be CRLF(0x0d0x0a)

**Comment by troygNZ** [comment]
Thanks @iwate  - I'll check this in the morning. The payload and response I obtained for you was from the OData monitoring tool within SAP C4C, so may not preserve it within the browser monitoring tool. I'll debug and reproduce in the IDE to ensure no tampering of response.
